<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/15 0015
 * Time: 上午 9:22
 */

namespace app\admin\controller;

use think\Request;

class BaseController extends \think\Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user = null;
        $userType = 0;


        $request = Request::instance();
        $module = $request->module();
        $method = $request->controller();
        $action = $request->action();


        if (!is_null(session('user'))) {
            $user = session('user');
            $userType = session('userType');
        } else {
            if ($method != 'Login') {
                $this->redirect('/admin/login/index');
            }
        }
        $this->assign('userType', $userType);
        $this->assign('user', $user);

    }
}