<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/13 0013
 * Time: 上午 10:26
 */

namespace app\index\controller;

use think\Controller;

class BaseController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user = null;
        $userType = 0;
        if (!is_null(session('user'))) {
            $user = session('user');
            $userType = session('userType');
        }
        $this->assign('userType', $userType);
        $this->assign('user', $user);

    }

}